services:
  budgeteer:
    image: anaschhilif/budgeteer:latest
    container_name: budgeteer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/budgeteerdb
      SPRING_DATASOURCE_USERNAME: budgeteeruser
      SPRING_DATASOURCE_PASSWORD: budgeteerpassword
      LOKI_URL: http://loki:3100/loki/api/v1/push
    depends_on:
      - postgres
      - loki

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: budgeteerdb
      POSTGRES_USER: budgeteeruser
      POSTGRES_PASSWORD: budgeteerpassword

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.procfs=/proc'
      - '--path.sysfs=/sys'

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /proc:/host/proc
      - /sys:/host/sys
    depends_on:
      - node_exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  loki-data:
  grafana-data:
