global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__address__]
        regex: (.*)
        target_label: instance
        replacement: host_machine

  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'budgeteer:8080' ]
