name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            echo "Starting deployment..."
            
          
            cd ${{ secrets.INFRA_PATH }}

            git stash

            git pull origin main
            
            
            cat > .env << EOF
            DEVAPI_URL=${{ secrets.DEVAPI_URL }}
            GRAFANA_URL=${{ secrets.GRAFANA_URL }}
            BOOKSTACK_URL=${{ secrets.BOOKSTACK_URL }}
            EMAIL=${{ secrets.EMAIL }}
            BOOKSTACK_APP_URL=${{ vars.BOOKSTACK_APP_URL }}
            BOOKSTACK_APP_KEY=${{ secrets.BOOKSTACK_APP_KEY }}
            BOOKSTACK_DB_HOST=${{ vars.BOOKSTACK_DB_HOST }}
            BOOKSTACK_DB_PORT=${{ vars.BOOKSTACK_DB_PORT }}
            BOOKSTACK_DB_USERNAME=${{ vars.BOOKSTACK_DB_USERNAME }}
            BOOKSTACK_DB_PASSWORD=${{ secrets.BOOKSTACK_DB_PASSWORD }}
            BOOKSTACK_DB_DATABASE=${{ vars.BOOKSTACK_DB_DATABASE }}
            BOOKSTACK_MYSQL_ROOT_PASSWORD=${{ secrets.BOOKSTACK_MYSQL_ROOT_PASSWORD }}
            EOF
            
      
            
            # Stop current containers
            docker compose down
            
            # Start with updated configuration
            docker compose up -d
            
            echo "Deployment completed successfully!"